# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
_extends: .github

# Override the template to include default tool versions
template: |
  <!-- Optional: add a release summary here -->
  
  ## Default Clang Tools Versions
  
  This release uses the following default versions:
  - **clang-format**: `$CLANG_FORMAT_VERSION`
  - **clang-tidy**: `$CLANG_TIDY_VERSION`
  
  Users can specify the desired version by adding the `--version` argument under `args` in their pre-commit configuration. See: [Custom Clang Tool Version](https://github.com/cpp-linter/cpp-linter-hooks?tab=readme-ov-file#custom-clang-tool-version)
  
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
