- id: clang-format
  name: clang-format
  description: formatting C/C++ code
  entry: clang-format-hook
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|c|cc|cpp|c\+\+|cxx)$
  types_or: [c, c++, c#, objective-c]

- id: clang-tidy
  name: clang-tidy
  description: diagnosing and fixing typical programming errors
  entry: clang-tidy-hook
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|c|cc|cpp|c\+\+|cxx)$
  types_or: [c, c++, c#, objective-c]
