repos:
  - repo: .
    rev: HEAD
    hooks:
      - id: clang-format
        args: [--style=file, --version=16]  # to load .clang-format
      - id: clang-tidy
        args: [--checks=.clang-tidy, --version=16] # path/to/.clang-tidy
  - repo: .
    rev: HEAD
    hooks:
      - id: clang-format
        args: [--style=file, --version=17]
      - id: clang-tidy
        args: [--checks=.clang-tidy, --version=17]
  - repo: .
    rev: HEAD
    hooks:
      - id: clang-format
        args: [--style=file, --version=18]
      - id: clang-tidy
        args: [--checks=.clang-tidy, --version=18]
  - repo: .
    rev: HEAD
    hooks:
      - id: clang-format
        args: [--style=file, --version=19]
      - id: clang-tidy
        args: [--checks=.clang-tidy, --version=19]
  - repo: .
    rev: HEAD
    hooks:
      - id: clang-format
        args: [--style=file, --version=20]
      - id: clang-tidy
        args: [--checks=.clang-tidy, --version=20]
  - repo: .
    rev: HEAD
    hooks:
      - id: clang-format
        args: [--style=file, --version=21]
      - id: clang-tidy
        args: [--checks=.clang-tidy, --version=20] # clang-tidy does not support version 21
