name: CodSpeed

on:
  push:
    branches:
      - "main"
    paths:
      - "cpp-linter-hooks/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "pyproject.toml"
  pull_request:
    branches:
      - "main"
    paths:
      - "cpp-linter-hooks/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "pyproject.toml"
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 #v5
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Install dependencies
        run: uv sync --dev

      - name: Run benchmarks
        uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 #4.18.5
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest tests/ --codspeed
          mode: simulation
