name: CodSpeed

on:
  push:
    branches:
      - "main"
    paths:
      - "cpp-linter-hooks/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "pyproject.toml"
  pull_request:
    branches:
      - "main"
    paths:
      - "cpp-linter-hooks/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "pyproject.toml"
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 #v5
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Install dependencies
        run: uv sync --dev

      - name: Run benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f #4.18.1
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest tests/ --codspeed
          mode: simulation
