name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write # trusted signing of build provenance attestations
      attestations: write
    uses: cpp-linter/.github/.github/workflows/py-publish.yml@main
    secrets: inherit
